### ISSUE TITLE
any results and instructions in readme?

### ISSUE THREAD

**Issue by lucasjinreal** [An-nay-marks/3DVision_2022#2]
any results and instructions in readme?

**Comment by lweitzendorf** [comment]
Hey! Sorry about that, the project is still in progress. We'll add some instructions soon. In its simplest configuration, you can run it from the root directory using `python reconstruct.py -s <video_file_path> [--online]`. We'll describe all of the arguments in the README once they are finalized. All dependencies should be listed in the environment.yml file. Let me know if you have any more questions.

**Comment by lweitzendorf** [comment]
For the missing model files, please refer to the usage section of https://github.com/YadiraF/DECA and copy them into data/model_files

**Comment by lucasjinreal** [comment]
@lweitzendorf thanks a lot. BTW, recently there are a lot of work on reconstruction 3d portrait, I found this work is pretty good. https://github.com/philgras/neural-head-avatars
How do u think it's pros can cons compare with this repo?

**Comment by lweitzendorf** [comment]
@jinfagang The biggest differentiator would be that our pipeline is designed to operate on more noisy, real-world data such as footage from TV shows and to detect and classify multiple people instead of a single person under close to ideal conditions. 

On the other hand, neural head avatars will have much better texture mapping since DECA, the reconstruction model we are using, is designed to recover detailed facial geometry rather than recreating a photorealistic avatar.

Having said that, our goal is to create a modular pipeline with interchangeable models at the detection, classification and reconstruction stage. Therefore, it would certainly be possible to support a model such as NHA for reconstruction in the future.

**Comment by lucasjinreal** [comment]
@lweitzendorf thanks for your reply.  What's the usage scenario on multiple person in a video? Can u point me what's NHA is?

**Comment by lweitzendorf** [comment]
@jinfagang Sorry for the confusion, NHA was short for Neural Head Avatars, the paper you linked. To be able to use footage from TV shows and other videos where multiple people might be in frame, we need the ability to detect more than one person in the video. It simply allows us to use any video (of reasonable quality) instead of requiring a separate video for each person whose head we want to reconstruct.

**Comment by lucasjinreal** [comment]
@lweitzendorf thanks, I hope to see your updated results. this modularized pipeline is promising.

**Comment by An-nay-marks** [comment]
Hi @jinfagang ,

we have finished our pipeline for now and added a ReadMe. The setup is currently quite tedious due to the many dependencies, but we might release a standalone app in the future if time allows.

Best,
Anne
